In [1]:
import time

import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5, -12])
2*x

array([  2,   4,   6,   8,  10, -24])

In [3]:
y = np.array([-7, 12, 6, 0, 9, 19])
x * y

array([  -7,   24,   18,    0,   45, -228])

In [4]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
        0.53657292])

In [5]:
x[2:]

array([  3,   4,   5, -12])

In [6]:
x

array([  1,   2,   3,   4,   5, -12])

In [7]:
x > 3

array([False, False, False,  True,  True, False])

In [8]:
x[x > 3]

array([4, 5])

In [9]:
N = 10000000
lst_x = list(range(N))

In [10]:
t0 = time.time()
lst_y = [x**2 for x in lst_x]
t1 = time.time()
print(t1 - t0)

2.6589672565460205


In [11]:
arr_x = np.arange(N)
arr_x

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [12]:
t0 = time.time()
arr_y = arr_x**2
t1 = time.time()
print(t1 - t0)

0.03413677215576172


In [13]:
a = np.arange(0, 24, 1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
b = a.reshape(4, 3, 2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [17]:
b + x

ValueError: operands could not be broadcast together with shapes (4,3,2) (6,) 

In [18]:
a.reshape(2, 3, 2, 2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [19]:
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [20]:
b[0, 2, 1]

np.int64(5)

In [21]:
b[2, ...]

array([[12, 13],
       [14, 15],
       [16, 17]])

In [23]:
b[:, 1 ,:]

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]])

In [25]:
b[:, 1:3 ,:]

array([[[ 2,  3],
        [ 4,  5]],

       [[ 8,  9],
        [10, 11]],

       [[14, 15],
        [16, 17]],

       [[20, 21],
        [22, 23]]])

In [27]:
np.linspace(0, 10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [28]:
np.logspace(-3, 2, 100)

array([1.00000000e-03, 1.12332403e-03, 1.26185688e-03, 1.41747416e-03,
       1.59228279e-03, 1.78864953e-03, 2.00923300e-03, 2.25701972e-03,
       2.53536449e-03, 2.84803587e-03, 3.19926714e-03, 3.59381366e-03,
       4.03701726e-03, 4.53487851e-03, 5.09413801e-03, 5.72236766e-03,
       6.42807312e-03, 7.22080902e-03, 8.11130831e-03, 9.11162756e-03,
       1.02353102e-02, 1.14975700e-02, 1.29154967e-02, 1.45082878e-02,
       1.62975083e-02, 1.83073828e-02, 2.05651231e-02, 2.31012970e-02,
       2.59502421e-02, 2.91505306e-02, 3.27454916e-02, 3.67837977e-02,
       4.13201240e-02, 4.64158883e-02, 5.21400829e-02, 5.85702082e-02,
       6.57933225e-02, 7.39072203e-02, 8.30217568e-02, 9.32603347e-02,
       1.04761575e-01, 1.17681195e-01, 1.32194115e-01, 1.48496826e-01,
       1.66810054e-01, 1.87381742e-01, 2.10490414e-01, 2.36448941e-01,
       2.65608778e-01, 2.98364724e-01, 3.35160265e-01, 3.76493581e-01,
       4.22924287e-01, 4.75081016e-01, 5.33669923e-01, 5.99484250e-01,
      

In [29]:
np.geomspace(1, 3, 10)

array([1.        , 1.12983096, 1.27651801, 1.44224957, 1.62949822,
       1.84105755, 2.08008382, 2.35014311, 2.65526446, 3.        ])

In [32]:
np.zeros((3, 4, 1, 5, 6))
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [33]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
A = np.eye(2)
A[1, 0] = 3
A

array([[1., 0.],
       [3., 1.]])

In [36]:
A.T

array([[1., 3.],
       [0., 1.]])

In [37]:
A @ np.array([2, 3])

array([2., 9.])

In [38]:
A @ A

array([[1., 0.],
       [6., 1.]])

In [40]:
b.shape

(4, 3, 2)

In [42]:
np.einsum('ij, klj', A, b)

array([[[ 0.,  2.,  4.],
        [ 6.,  8., 10.],
        [12., 14., 16.],
        [18., 20., 22.]],

       [[ 1.,  9., 17.],
        [25., 33., 41.],
        [49., 57., 65.],
        [73., 81., 89.]]])

In [43]:
np.concat([np.linspace(0, 1, 10), np.logspace(0, 1, 10)])

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ,
        1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

In [45]:
x=np.geomspace(1, 5, 10)

In [46]:
x[1:]

array([1.19581317, 1.42996915, 1.70997595, 2.04481177, 2.44521285,
       2.92401774, 3.49657893, 4.18125515, 5.        ])

In [47]:
x[:-1]

array([1.        , 1.19581317, 1.42996915, 1.70997595, 2.04481177,
       2.44521285, 2.92401774, 3.49657893, 4.18125515])

In [50]:
x[1:]/x[:-1]

array([1.19581317, 1.19581317, 1.19581317, 1.19581317, 1.19581317,
       1.19581317, 1.19581317, 1.19581317, 1.19581317])

In [52]:
a = np.linspace(-5, 5, 100)

In [54]:
np.argmin(a**2)

np.int64(49)

In [ ]:
A = list(range(200000000))

: 

In [1]:
import numpy as np
np.arange(20000000)

array([       0,        1,        2, ..., 19999997, 19999998, 19999999])

In [2]:
x = np.arange(5)
y = np.arange(6)
x

array([0, 1, 2, 3, 4])

In [3]:
y

array([0, 1, 2, 3, 4, 5])

In [4]:
X, Y = np.meshgrid(x, y)

In [5]:
X

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [6]:
Y

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [7]:
X + 1j * Y

array([[0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [0.+1.j, 1.+1.j, 2.+1.j, 3.+1.j, 4.+1.j],
       [0.+2.j, 1.+2.j, 2.+2.j, 3.+2.j, 4.+2.j],
       [0.+3.j, 1.+3.j, 2.+3.j, 3.+3.j, 4.+3.j],
       [0.+4.j, 1.+4.j, 2.+4.j, 3.+4.j, 4.+4.j],
       [0.+5.j, 1.+5.j, 2.+5.j, 3.+5.j, 4.+5.j]])

In [8]:
X**2 + Y**2

array([[ 0,  1,  4,  9, 16],
       [ 1,  2,  5, 10, 17],
       [ 4,  5,  8, 13, 20],
       [ 9, 10, 13, 18, 25],
       [16, 17, 20, 25, 32],
       [25, 26, 29, 34, 41]])

In [9]:
np.inf

inf

In [10]:
2*np.inf

inf

In [11]:
np.inf + np.inf

inf

In [12]:
np.inf - np.inf

nan

In [13]:
np.nan

nan

In [14]:
0 == np.nan

False

In [15]:
np.nan > 0

False

In [16]:
np.nan < 0

False

In [17]:
np.nan == np.nan

False

In [18]:
-np.inf

-inf

In [19]:
1/np.inf

0.0

In [20]:
1/-np.inf

-0.0

In [22]:
0**0

1

In [25]:
1/np.nan

nan